### ISSUE TITLE
Early feedback on API design

### ISSUE THREAD

**Issue by jasononeil** [jasononeil/dodrugs#10]
I'd love to get some early feedback before progressing further. If I'm going to make any big changes to the API design now is the best time to do so!

Questions:
1. What do you think of the idea that you can only set up in injector in one place, and you can never add or remove mappings from it? (But you can extend it / create a child injector)
2. What do you think of each injector having a generic type `Injector<"myapp">`? Does it make sense to you? Can you think of a better way to separate the different injectors so the compiler knows which one is which?
3. What do you think of the syntax for mapping APIs, to a value, a singleton, a class?
   
   At the moment we have three options: 
   - `String.named("sessionName").toValue(name)`
   - `(sessionName:String).toValue(name)`
   - `MyClass` (class mapping short hand)
   
   Which of these do you like best? Can you think of a better syntax?
4. The @inject points. I've followed minject, but would you do anything different? Support `@:inject` instead as well? Handle named injector mappings differently? Etc.
5. Anything else?

cc @kevinresol @francescoagati (and maybe @back2dos because you're always full of good ideas)

**Comment by kevinresol** [comment]
For 2, does that mean if the compiler knows about it, it can warn me like "there is no mapping for `MyClass`" when I write `injector.get(MyClass)`? 

Another way to let the compiler distinguish would be `MyInjector extends dodrugs.Injector`. (maybe that is already the case under the hood? I didn't check into the details)

Currently the mappings are stored in a map, which is runtime thing. What if we translate all the mappings in to a function call? e.g. a mapping of `MyClass` will get translated into a member method in the injector `function get_MyClass(?name)`. Then "extend" will literally mean extending another injector class, so that it will fallback to parent's mapping when the method is not overridden. The `get(type, name)` call will then become a macro that translates into `get_MyClass(name)`. In that case all dirty works are nicely handled by the type system.

So far I feel like home when switching from minject. The only thing that bothers me is https://github.com/jasononeil/dodrugs/issues/2.

**Comment by jasononeil** [comment]
I really like that idea!

I'd been intending to use compile time metadata to track what mappings are required and what mappings are supplied, and during then check they match during `onGenerate` or something.

We could still do that using these functions: https://github.com/jasononeil/dodrugs/blob/master/src/dodrugs/InjectorMacro.hx#L291-L299

But your alternative solution sounds good.  
1. `Injector<"myapp">` is generic-built into `class Injector_myapp extends InjectorInstance { /** with mapping functions...**/ }`
2. `injector.get( Person.named("jason") )` is transformed into `injector.getPerson_named_jason()`

It takes care of extension/inheritence and it would guarantee compiletime safety.  The generated code would be really clean too, moreso than using a map like it does now.

One possible issue: We need to make sure that the mappings are available when the class is built, so we can generate the new functions.  If we keep using @:genericBuild, the only information we have available when we build is the type parameter(s) used.  We could switch to using a class definition to set up your injector:

``` haxe
class MyAppInjector extends Injector {
    @value var sessionExpiry:Int = 3600;
    @singleton var _:MailApi;
    @class var _:UserController;
}
```

But that doesn't really work for more complex `toValue()` mappings, where we might want to pass in a local variable.  Think `Mysql.connect( Json.parse(File.getContent("dbconf.json")) )`.  At some point working in a variable initialisation expression isn't practical.

Any ideas?

**Comment by kevinresol** [comment]
I think we still use `Injector.create` and `Injector.extend` as the user-facing interface. Just that under the hood they get generic-built to a class. Values for `toValue()` will be passed as params to the class's init/constructor so they get stored in the class as member variables.

**Comment by jasononeil** [comment]
The issue we have is build order.  We can't guarantee that `Injector.create()` will be called before the `@:genericBuild` for that injector.

I just pushed an example to demonstrate the problem, see [this commit](https://github.com/jasononeil/dodrugs/commit/9bd41862bc933e8dbf574a853ffd7a8128258c98), which gives the output:

```
src/dodrugs/InjectorMacro.hx:21: Injector.create("exampleInjector", ...)
src/dodrugs/InjectorBuildMacro.hx:17: @:genericBuild for Injector<"exampleInjector">
src/dodrugs/InjectorMacro.hx:21: Injector.create("test-example-2", ...)
src/dodrugs/InjectorBuildMacro.hx:17: @:genericBuild for Injector<"test-example-2">
src/dodrugs/InjectorMacro.hx:21: Injector.create("my-app-injector", ...)
src/dodrugs/InjectorBuildMacro.hx:17: @:genericBuild for Injector<"my-app-injector">
src/dodrugs/InjectorMacro.hx:21: Injector.create("ufront-app-injector", ...)
src/dodrugs/InjectorBuildMacro.hx:17: @:genericBuild for Injector<"ufront-app-injector">
src/dodrugs/InjectorMacro.hx:21: Injector.create("singleton test", ...)
src/dodrugs/InjectorBuildMacro.hx:17: @:genericBuild for Injector<"singleton test">
src/dodrugs/InjectorBuildMacro.hx:17: @:genericBuild for Injector<"classInstantiationInjector">
test/InjectionTestClasses.hx:141: characters 29-75 : Type not found : dodrugs.injector.classInstantiationInjector
```

I'm not sure if there's a workaround without doing something confusing...

**Comment by kevinresol** [comment]
I am yet have time to read into details,  but tink_json achieved something similar.  We may reference that.

**Comment by jasononeil** [comment]
Another tink library that I hadn't seen before! Amazing stuff.

In this case I think the parser and reader use @:genericBuild but they always know the expected type.  For example,

``` haxe
var o:{ foo: Int, bar:Array<{ flag: Bool }> } = tink.Json.parse('...');
```

Will generate a `tink.json.Parser<{ foo: Int, bar:Array<{ flag: Bool }> }>`. And

``` haxe
var greeting = { hello: 'world', foo: 42 };
var limited:{ hello:String } = greeting;
trace(tink.Json.stringify(greeting));//{"hello":"world"}
```

will generate a `tink.json.Writer<{ hello:String }>`.  So in both cases the type parameter of the `@:genericBuild` has all the information it needs to build the type.  In our case the type parameter is just a string, and the information needed to build the type is only available in the place where `Injector.create()` is called.

Short of making the type parameter the actual available types (`Injector<{ _:MailApi, _:UFMailer, app:UfrontApplication }>`) I'm not sure we can get this to work.

Unless there's something I'm missing?

**Comment by jasononeil** [comment]
The only way I think it will work is for the Injector to be declared in a class declaration rather than a macro function call:

``` haxe
class MyAppInjector extends Injector {
    @value var sessionExpiry:Int = 3600;
    @singleton var _:UFMailer = new SmtpMailer();
    @singleton var _:MailApi;
    @class var _:UserController;
}
class MyApp {
    static function main() {
        var inj = new MyAppInjector();
    }
}
```

The advantages:
- The mental model is much easier (each injector is a class, it can extend other classes)
- It is also much easier to understand that mappings are set once and can't be changed (you can't change a class at runtime, you can't change an injector at runtime).
- By generating a function for each mapping, we have clean fields rather than DynamicAccess<Function>. Much nicer generated code, and probably better performance.

The disadvantages:
- The syntax for mapping a class to itself, with no name, is clunky: `@class var _:UserController;`
- Every syntax I can think of for setting a "toValue()" seems clunky.  You could do:

``` haxe
class MyAppInjector extends Injector {
    @value var sessionName:String = constructor; // Could also macros to do a clearer easier syntax
}
class MyApp {
    static function main() {
        sessionName = getSessionName();
        var inj = new MyAppInjector( getSessionName() );
    }
}
```

But it's still a bit confusing, it's not how you'd expect it to work.  I really, really liked the idea, but with the build order issue I can't get a syntax that feels clean and obvious.  Which is a shame...

**Comment by francescoagati** [comment]
but we can inject also complex objets?
for example

```
class MyAppInjector extends Injector {
    @value var sessionExpiry:Int = 3600;
    @singleton var _:UFMailer = (functon() {
            var mailer = new SmtpMailer();
            mailer.set('value',2);
             return mailer;
     });
    @singleton var _:MailApi;
    @class var _:UserController;
}
class MyApp {
    static function main() {
        var inj = new MyAppInjector();
    }
}


```

**Comment by jasononeil** [comment]
@francescoagati Yes I guess that would work, and would cover many use cases (maybe even most?)

What do you think?  Would you prefer the

```
class MyAppInjector extends Injector {...}
```

syntax or the

```
Injector.create( "myapp", {} );
```

syntax?  Keeping in mind the "class" syntax would have quite nice code generation..

**Comment by francescoagati** [comment]
i prefer class MyAppInjector extends Injector {...} is more haxe style

**Comment by kevinresol** [comment]
I am thinking that the class declaration way may render `toValue()` pretty useless. Because `toValue()` seems to be scope-aware usually. Maybe I am wrong, I dunno.

**Comment by kevinresol** [comment]
Give me a day or two and see if I can write something

**Comment by jasononeil** [comment]
That's my main concern too - toValue() seems really hard to use.  You could do something like:

``` haxe
class MyAppInjector extends Injector {
    @value var sessionExpiry:Int = 3600;
    @singleton var _:UFMailer = mailer; // reference local scope when create() is called
    @singleton var _:MailApi;
    @class var _:UserController;
}
class MyApp {
    static function main() {
        var mailer = new SmtpMailer();
        mailer.set('value',2);
        var inj = new MyAppInjector.create();
    }
}
```

but I think that's not obvious enough.

Let's both see if we come up with something in the next few days :)  Otherwise we'll stick to the `Injector.create("myapp")` syntax and use metadata to track usages and give compiletime warnings.

**Comment by kevinresol** [comment]
Hm, I think there is no way to use macro to build class that extends another (which is also macro-built), with random order of appearance of the macro call. Consider this:

``` haxe
// Main.hx
class Main {
  var test:Test;
  static function main(){
    Injector.create('parent', [...]);
  }
}

// Test.hx
class Test {
  public function new() {
    Injector.extend('child','parent',[...]);
  }
}
```

The compiler first compiles `Main.hx`. It tries to type `Test` when it encounters `var test:Test`. Inside `Test` we declare `class Child extends Parent` through `Injector.extend()`. At this point the compiler complains that `Parent` is not defined, because `Parent` will be declared through `Injector.create()` only when the compiler types `Main.main()`

**Comment by jasononeil** [comment]
@kevinresol yes that's the same conclusion I came to.  I'll go ahead with the metadata based approach to compiletime safety.

I've implemented some initial working code.  Need more tests and fixes still, especially for:
- [ ] Working with the compiler cache
- [ ] Working with parent injectors

**Comment by kevinresol** [comment]
Is there a way to do `injectInto` as in minject?
I have some classes that are constructed from `haxe.Unserializer.run()`, where their attributes are populated. But their functionalities are to be injected by DI.

**Comment by jasononeil** [comment]
After not touching the project for 9 months and coming back to it, I felt pretty confident to go ahead with constructor injection only.  This means leaving behind any concept on `@inject` metadata, and basing it solely off constructors, their arguments (types and names).

So some of the semantics have changed, and I think I've settled on better syntax.  Check the README to see what I mean.

In terms of some of the things like supporting `injectInto`, I think the approach would be something like:

```
class MySerializableClass {
     var isSerialized:String;
     var isSerialized2:Int;
     @:skip var myApi1:Api1;
     @:skip var myApi2:Api2;

     public function injectApis(inj:Injector) {
         this.myApi1 = inj.get(Api1);
         this.myApi2 = inj.get(Api2);
     }
}

var myObj:MySerializableClass = haxe.Unserializer.run(serializedStr);
myObj.injectApis(injector);
```
