### ISSUE TITLE
Feature request: Singletons scoped to child injectors

### ISSUE THREAD

**Issue by kevinresol** [jasononeil/dodrugs#11]
say we have three injectors:
- parent: defines a singleton mapping
- child1 extends parent
- child2 extends parent

Then will the following give me the same instance?

``` haxe
child1.getValue(ThatSingletonClass)
child2.getValue(ThatSingletonClass)
```

If yes, it is possible to have a mapping rule like `toScopedSingleton` such that the singleton scope will be within each child injector? i.e. the above code will give me two different instances.

**Comment by jasononeil** [comment]
I'm open to this idea - what's the main use case you have in mind?
