### ISSUE TITLE
passing an initialized object

### ISSUE THREAD

**Issue by francescoagati** [jasononeil/dodrugs#12]
hi. there is a mode for passing an object preinitializated with other values to the injector?

for example

var a = new A();
a.x = 1;
a.y = 2;
Injector.set(a,A); where the object overrde or add the new fields?

**Comment by jasononeil** [comment]
Hi @francescoagati,

Sorry I never replied earlier - I've only just come back to finishing this library.  I decided to go with an approach where the focus is entirely on constructor injection, so this kind of pattern doesn't make as much sense here.

Kevin asked a similar question, comparing it to minject's "injectInto()" method, and I proposed one solution for his use case:

https://github.com/jasononeil/dodrugs/issues/10#issuecomment-297198554

I don't think I want to support this as a major feature going forward, but if there was an elegant way to have a separate macro that finds some injection points on existing objects I am not opposed.
