### ISSUE TITLE
'haxe.DynamicAccess' implies use of reflection

### ISSUE THREAD

**Issue by piotrpawelczyk** [jasononeil/dodrugs#13]
Readme states that one of the goals of the library is to avoid usage of reflection. Yet `dodrugs.InjectorMappings` is basically a `haxe.DynamicAccess`, which generates some reflection calls. Specifically `dodrugs.UntypedInjector._get` compiles to the following PHP code:
```
	public function _get ($id) {
		$wildcardId = (HxString::split($id, " ")->arr[0] ?? null);
		if (\Reflect::hasField($this->mappings, $id)) {
			return \Reflect::field($this->mappings, $id)($this, $id);
		} else if (($wildcardId !== $id) && \Reflect::hasField($this->mappings, $wildcardId)) {
			return \Reflect::field($this->mappings, $wildcardId)($this, $wildcardId);
		} else if ($this->parent !== null) {
			return $this->parent->getFromId($id);
		} else {
			throw new HxException("The injection had no mapping for \"" . ($id??'null') . "\"");
		}
	}
```

Is this deliberate or are you planning to change this? Btw. Haxe docs clearly say that `haxe.DynamicAccess` "basically, wraps Reflect calls in a Map-like interface".

**Comment by jasononeil** [comment]
@szczepanpp sorry I guess I should clarify that the goal there is to avoid:

1. Unsafe reflection which could result in runtime errors
2. Avoid reflection entirely on JS to keep download size small.

I actually don't mind this reflection as much for server side targets as long as it is completely safe, as the size of the generated code is not much of an issue.  In this case it is limited to DynamicAccess which is a pretty safe limited and safe approach.

I'll update the README to show this.

Thanks for reporting though!
