### ISSUE TITLE
Mapping functions and typedefs

### ISSUE THREAD

**Issue by piotrpawelczyk** [jasononeil/dodrugs#14]
I'm able to inject about any runtime object using `Any` named mappings but obviously I'm loosing any type safety that way. Would you consider allowing mappings specified by function signature?

Also it would be nice to support typedefs and anonymous type declarations - if it's only possible, of course.

**Comment by jasononeil** [comment]
Hey @szczepanpp 

You can actually already inject typedefs, anonymous structures, and functions, like this:

```haxe
return Injector.create("exampleInjector", [
	var cb:String->Void = function (str) trace(str),
	var anon:{age:Int} = {age:28},
	var typedef:MyTypedef = {}
]);
```

Let me know if you have any issues with this
