### ISSUE TITLE
Doesn't work with compilation server

### ISSUE THREAD

**Issue by kevinresol** [jasononeil/dodrugs#4]
Seems that the injector names are cached and it complains `An Injector named "name" was previously created here` on second compilation

**Comment by jasononeil** [comment]
Running

```
 haxe --connect 6000 test.hxml && neko bin/test.n
 haxe --connect 6000 test.hxml && neko bin/test.n
```

Twice in a row works for me.  In theory this is supposed to take care of the compiler cache (though I had not tested it until just now): https://github.com/jasononeil/dodrugs/blob/master/src/dodrugs/InjectorMacro.hx#L357

I've just added a travis build file.  Is there an easy way to test compiling twice, using the cache, in a travis build?

**Comment by kevinresol** [comment]
Hm... Let me inspect it again and see if I can reproduce it reliably

**Comment by kevinresol** [comment]
Btw, [travix](https://github.com/back2dos/travix) may help you simplify things a bit (your yml can be as simple as [this](https://github.com/kevinresol/geojson/blob/master/.travis.yml))

**Comment by jasononeil** [comment]
This has been working well for me locally, so I'm going to close the issue.  

Should definitely set up travis (and travix) soon though
